---
title: "Impressum"
---

## Herausgeber

Berlin-Brandenburgische Akademie der Wissenschaften, 
Jägerstraße 22/23, 
10117 Berlin

## Vertreter

Prof. Dr. Dr. h.c. mult. Christoph Markschies
Tel.: +49 30 20370-0, E-Mail: [bbaw@bbaw.de](mailto:bbaw@bbaw.de)

## Rechtsform

Rechtsfähige Körperschaft öffentlichen Rechts
Umsatzsteuer-Identifikationsnummer

DE 167 449 058 (gemäß §27 a Umsatzsteuergesetz)

## Technische Realisierung

Dr. Annette von Stockhausen (AV Die alexandrinische und antiochenische Bibelexegese in der Spätantike)

## Urheberrecht

Die BBAW ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Video-Sequenzen und Texte zu beachten, von ihm selbst erstellte Grafiken, Tondokumente, Video-Sequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Video-Sequenzen und Texte zurückzugreifen.

Alle innerhalb des Internet-Angebotes genannten und gegebenenfalls durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer.

Allein aufgrund der bloßen Nennung ist nicht der Schluß zu ziehen, daß Markenzeichen nicht durch Rechte Dritter geschützt sind.

Das Copyright für veröffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten.

Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Video-Sequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet, wenn es den zulässigen Umfang überschreitet oder den zulässigen Zweck nicht erfüllt.

## Hinweise zum Datenschutz

Bei jedem Zugriff eines Nutzers auf das Internet-Angebot der Berlin-Brandenburgischen Akademie der Wissenschaften und bei jedem Abruf einer Datei werden Daten über diesen Vorgang technisch bedingt vorübergehend in einer Protokolldatei gespeichert und verarbeitet:
*  die IP-Adresse (diese wird unmittelbar nach dem Zugriff anonymisiert)
*  Datum und Uhrzeit
*  aufgerufene Seite/Name der abgerufenen Datei
*  übertragene Datenmenge
*  Meldung, ob der Zugriff/Abruf erfolgreich war
Zweck der Datenerhebung ist der verpflichtende Schutz vor Angriffen des Netzwerks, die Verbesserung des Angebots sowie die Erstellung von Nutzungsstatistiken. Diese Daten werden eine Woche gespeichert.

Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 S. 1 lit. b DSGVO (Erforderlichkeit zur Wahrung berechtigter Interessen).

Für das reibungslose Funktionieren einiger Seiten müssen Cookies gesetzt werden. Diese Cookies beinhalten keine personenbezogenen Daten und werden nicht weiter ausgewertet. Da es sich um eine technische Notwendigkeit handelt, bedarf es keiner ausdrücklichen Zustimmung durch den Nutzer.

Diese Website benutzt Matomo (vormals Piwik), eine Open-Source-Software zur statistischen Auswertung der Besucherzugriffe. Matomo verwendet keine Tracker Cookies (Es arbeitet mit der Funktion: Tracking ohne Cookies erzwingen)! 
Die IP-Adresse wird sofort nach der Verarbeitung und vor deren Speicherung anonymisiert.

Zweck der Datenerhebung ist die Verbesserung des Angebots sowie die Erstellung von Nutzungsstatistiken. Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 S. 1 lit. b DSGVO (Erforderlichkeit zur Wahrung berechtigter Interessen).
